apiVersion: v1
kind: Service
metadata:
  name: salvador-api-service
  namespace: salvador
  labels:
    app: salvador-api
spec:
  selector:
    app: salvador
  type: NodePort
  ports:
    - port: 80               
      protocol: TCP
      targetPort: 8080       
      nodePort: 30080        
